// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	socialgraph "git.garena.com/sea-labs-id/batch-02/andreas-timothy/assignment-activity-reporter/socialgraph"
	mock "github.com/stretchr/testify/mock"
)

// FollowersNotifier is an autogenerated mock type for the FollowersNotifier type
type FollowersNotifier struct {
	mock.Mock
}

// NotifyLike provides a mock function with given fields: _a0, _a1
func (_m *FollowersNotifier) NotifyLike(_a0 *socialgraph.User, _a1 *socialgraph.User) {
	_m.Called(_a0, _a1)
}

// NotifyUpload provides a mock function with given fields: _a0
func (_m *FollowersNotifier) NotifyUpload(_a0 *socialgraph.User) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewFollowersNotifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewFollowersNotifier creates a new instance of FollowersNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFollowersNotifier(t mockConstructorTestingTNewFollowersNotifier) *FollowersNotifier {
	mock := &FollowersNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
