// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	parking "git.garena.com/sea-labs-id/batch-02/shared-projects/go-exercise-parking-lot/parking"
	mock "github.com/stretchr/testify/mock"
)

// LotAvailableNotifier is an autogenerated mock type for the LotAvailableNotifier type
type LotAvailableNotifier struct {
	mock.Mock
}

// NotifyLotAvailable provides a mock function with given fields: _a0
func (_m *LotAvailableNotifier) NotifyLotAvailable(_a0 *parking.Lot) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewLotAvailableNotifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewLotAvailableNotifier creates a new instance of LotAvailableNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLotAvailableNotifier(t mockConstructorTestingTNewLotAvailableNotifier) *LotAvailableNotifier {
	mock := &LotAvailableNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
