// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	parking "git.garena.com/sea-labs-id/batch-02/shared-projects/go-exercise-parking-lot/parking"
	mock "github.com/stretchr/testify/mock"
)

// LotFullNotifier is an autogenerated mock type for the LotFullNotifier type
type LotFullNotifier struct {
	mock.Mock
}

// NotifyLotFull provides a mock function with given fields: _a0
func (_m *LotFullNotifier) NotifyLotFull(_a0 *parking.Lot) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewLotFullNotifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewLotFullNotifier creates a new instance of LotFullNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLotFullNotifier(t mockConstructorTestingTNewLotFullNotifier) *LotFullNotifier {
	mock := &LotFullNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
